### ISSUE TITLE
Cryptic error - "Unknown application error occurred"

### ISSUE THREAD

**Issue by Vadorequest** [lambci/node-custom-lambda#14]
Here are the logs of my app when I try to reach my lambda:
```
REPORT RequestId: 1274b44b-b585-4a59-89a4-22e86460a5eb  Duration: 6866.84 ms    Billed Duration: 6900 ms        Memory Size: 512 MB     Max Memory Used: 162 MB 

Unknown application error occurred
Error
START RequestId: 48a19299-ac57-4f05-b747-2cd3118a4851 Version: $LATEST
END RequestId: 48a19299-ac57-4f05-b747-2cd3118a4851
REPORT RequestId: 48a19299-ac57-4f05-b747-2cd3118a4851  Duration: 6835.13 ms    Billed Duration: 6900 ms        Memory Size: 512 MB     Max Memory Used: 161 MB 

Unknown application error occurred
Error
START RequestId: e94accec-fb7d-407b-8dca-07b1c8ec7cec Version: $LATEST
END RequestId: e94accec-fb7d-407b-8dca-07b1c8ec7cec
REPORT RequestId: e94accec-fb7d-407b-8dca-07b1c8ec7cec  Duration: 6816.46 ms    Billed Duration: 6900 ms        Memory Size: 512 MB     Max Memory Used: 162 MB 

Unknown application error occurred
Error
START RequestId: 48f6b0a5-b9e3-44a6-b510-d19d476d694a Version: $LATEST

```

It happened after I changed the `--target` option of one of my scripts in my `serverless.yml`:

```yml

  webpack:
    packager: 'yarn'
    packagerOptions:
      # XXX Necessary to properly package the "node-v48-linux-x64-glibc" binary used by "dialogflow", because AWS Lambda runs under Linux
      # See https://github.com/serverless-heaven/serverless-webpack/issues/342#issuecomment-383248835
      scripts:
        - npm rebuild grpc --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc
```

This script tries to rebuild the grpc binary using a node target of 8.1.0 while running under a 10.15.3 nodejs version. It's perfectly normal that it fails, but the error message should be more understandable. 

I'm using https://github.com/serverless-heaven/serverless-webpack#custom-scripts to execute the scripts.

I have no idea how it can be improved, but I'd suggest to try to pinpoint the cause of the error in such use case, because if anyone migrate from an official runtime to this custom runtime and encounters this error they'll have a very hard time figuring out the root cause.
